/* soapServer.cpp
   Generated by gSOAP 2.8.15 from wsModuloAfore.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.15 2019-06-26 17:55:53 GMT")


extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:consultarAfiliado"))
		return soap_serve_ns2__consultarAfiliado(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:consultarSaldos"))
		return soap_serve_ns2__consultarSaldos(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:ObtenerFolioServicio"))
		return soap_serve_ns2__ObtenerFolioServicio(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:ValidarConvivenciaMarcaOperativa"))
		return soap_serve_ns2__ValidarConvivenciaMarcaOperativa(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:ObtenerSaldoDiarioRetiroParcial"))
		return soap_serve_ns2__ObtenerSaldoDiarioRetiroParcial(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:ValidarResolucionImss"))
		return soap_serve_ns2__ValidarResolucionImss_(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:MontosFechasDatamart"))
		return soap_serve_ns2__MontosFechasDatamart_(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:consultarResolucion"))
		return soap_serve_ns2__consultarResolucion(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:ConsultarComplementoResolucion"))
		return soap_serve_ns2__ConsultarComplementoResolucion(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:ConsultarResolucionTotalImss"))
		return soap_serve_ns2__ConsultarResolucionTotalImss(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:COperacionesPmg"))
		return soap_serve_ns2__COperacionesPmg(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:movimientosCuentas"))
		return soap_serve_ns2__movimientosCuentas(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:ConsultarResolucionTotalIssste"))
		return soap_serve_ns2__ConsultarResolucionTotalIssste(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:consultarSaldosPmg"))
		return soap_serve_ns2__consultarSaldosPmg(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:consultarAportaciones"))
		return soap_serve_ns2__consultarAportaciones(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:ConsultarResolucionTotalImssRI"))
		return soap_serve_ns2__ConsultarResolucionTotalImssRI(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:ConsultarSieforeCtaRegimen"))
		return soap_serve_ns2__ConsultarSieforeCtaRegimen(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:ConsultarSaldoVol"))
		return soap_serve_ns2__ConsultarSaldoVol(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:ConsultaSaldoVivienda"))
		return soap_serve_ns2__ConsultaSaldoVivienda(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:ConsultaAportacionesPosteriores"))
		return soap_serve_ns2__ConsultaAportacionesPosteriores(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:CConsultarResolusionRetAportaciones"))
		return soap_serve_ns2__CConsultarResolusionRetAportaciones(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:CConsultarSaldoRecuperar"))
		return soap_serve_ns2__CConsultarSaldoRecuperar(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:CConsultarFechaLiquida"))
		return soap_serve_ns2__CConsultarFechaLiquida(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:CConsultarNumMensualidad"))
		return soap_serve_ns2__CConsultarNumMensualidad(soap);
	if (!soap_match_tag(soap, soap->tag, "ns2:consultarSaldosPenMinGar"))
		return soap_serve_ns2__consultarSaldosPenMinGar(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__consultarAfiliado(struct soap *soap)
{	struct ns2__consultarAfiliado soap_tmp_ns2__consultarAfiliado;
	struct ns2__consultarAfiliadoResponse _param_1;
	soap_default_ns2__consultarAfiliadoResponse(soap, &_param_1);
	soap_default_ns2__consultarAfiliado(soap, &soap_tmp_ns2__consultarAfiliado);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__consultarAfiliado(soap, &soap_tmp_ns2__consultarAfiliado, "ns2:consultarAfiliado", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__consultarAfiliado(soap, soap_tmp_ns2__consultarAfiliado.in, _param_1);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__consultarAfiliadoResponse(soap, &_param_1);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__consultarAfiliadoResponse(soap, &_param_1, "ns2:consultarAfiliadoResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__consultarAfiliadoResponse(soap, &_param_1, "ns2:consultarAfiliadoResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__consultarSaldos(struct soap *soap)
{	struct ns2__consultarSaldos soap_tmp_ns2__consultarSaldos;
	struct ns2__consultarSaldosResponse _param_2;
	soap_default_ns2__consultarSaldosResponse(soap, &_param_2);
	soap_default_ns2__consultarSaldos(soap, &soap_tmp_ns2__consultarSaldos);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__consultarSaldos(soap, &soap_tmp_ns2__consultarSaldos, "ns2:consultarSaldos", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__consultarSaldos(soap, soap_tmp_ns2__consultarSaldos.inParam, _param_2);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__consultarSaldosResponse(soap, &_param_2);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__consultarSaldosResponse(soap, &_param_2, "ns2:consultarSaldosResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__consultarSaldosResponse(soap, &_param_2, "ns2:consultarSaldosResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__ObtenerFolioServicio(struct soap *soap)
{	struct ns2__ObtenerFolioServicio soap_tmp_ns2__ObtenerFolioServicio;
	struct ns2__ObtenerFolioServicioResponse _param_3;
	soap_default_ns2__ObtenerFolioServicioResponse(soap, &_param_3);
	soap_default_ns2__ObtenerFolioServicio(soap, &soap_tmp_ns2__ObtenerFolioServicio);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__ObtenerFolioServicio(soap, &soap_tmp_ns2__ObtenerFolioServicio, "ns2:ObtenerFolioServicio", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__ObtenerFolioServicio(soap, soap_tmp_ns2__ObtenerFolioServicio.inFoliador, _param_3);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__ObtenerFolioServicioResponse(soap, &_param_3);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__ObtenerFolioServicioResponse(soap, &_param_3, "ns2:ObtenerFolioServicioResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__ObtenerFolioServicioResponse(soap, &_param_3, "ns2:ObtenerFolioServicioResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__ValidarConvivenciaMarcaOperativa(struct soap *soap)
{	struct ns2__ValidarConvivenciaMarcaOperativa soap_tmp_ns2__ValidarConvivenciaMarcaOperativa;
	struct ns2__ValidarConvivenciaMarcaOperativaResponse _param_4;
	soap_default_ns2__ValidarConvivenciaMarcaOperativaResponse(soap, &_param_4);
	soap_default_ns2__ValidarConvivenciaMarcaOperativa(soap, &soap_tmp_ns2__ValidarConvivenciaMarcaOperativa);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__ValidarConvivenciaMarcaOperativa(soap, &soap_tmp_ns2__ValidarConvivenciaMarcaOperativa, "ns2:ValidarConvivenciaMarcaOperativa", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__ValidarConvivenciaMarcaOperativa(soap, soap_tmp_ns2__ValidarConvivenciaMarcaOperativa.inParam, _param_4);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__ValidarConvivenciaMarcaOperativaResponse(soap, &_param_4);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__ValidarConvivenciaMarcaOperativaResponse(soap, &_param_4, "ns2:ValidarConvivenciaMarcaOperativaResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__ValidarConvivenciaMarcaOperativaResponse(soap, &_param_4, "ns2:ValidarConvivenciaMarcaOperativaResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__ObtenerSaldoDiarioRetiroParcial(struct soap *soap)
{	struct ns2__ObtenerSaldoDiarioRetiroParcial soap_tmp_ns2__ObtenerSaldoDiarioRetiroParcial;
	struct ns2__ObtenerSaldoDiarioRetiroParcialResponse _param_5;
	soap_default_ns2__ObtenerSaldoDiarioRetiroParcialResponse(soap, &_param_5);
	soap_default_ns2__ObtenerSaldoDiarioRetiroParcial(soap, &soap_tmp_ns2__ObtenerSaldoDiarioRetiroParcial);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__ObtenerSaldoDiarioRetiroParcial(soap, &soap_tmp_ns2__ObtenerSaldoDiarioRetiroParcial, "ns2:ObtenerSaldoDiarioRetiroParcial", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__ObtenerSaldoDiarioRetiroParcial(soap, soap_tmp_ns2__ObtenerSaldoDiarioRetiroParcial.inParam, _param_5);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__ObtenerSaldoDiarioRetiroParcialResponse(soap, &_param_5);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__ObtenerSaldoDiarioRetiroParcialResponse(soap, &_param_5, "ns2:ObtenerSaldoDiarioRetiroParcialResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__ObtenerSaldoDiarioRetiroParcialResponse(soap, &_param_5, "ns2:ObtenerSaldoDiarioRetiroParcialResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__ValidarResolucionImss_(struct soap *soap)
{	struct ns2__ValidarResolucionImss_ soap_tmp_ns2__ValidarResolucionImss_;
	struct ns2__ValidarResolucionImssResponse _param_6;
	soap_default_ns2__ValidarResolucionImssResponse(soap, &_param_6);
	soap_default_ns2__ValidarResolucionImss_(soap, &soap_tmp_ns2__ValidarResolucionImss_);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__ValidarResolucionImss_(soap, &soap_tmp_ns2__ValidarResolucionImss_, "ns2:ValidarResolucionImss", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__ValidarResolucionImss_(soap, soap_tmp_ns2__ValidarResolucionImss_.inParam, _param_6);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__ValidarResolucionImssResponse(soap, &_param_6);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__ValidarResolucionImssResponse(soap, &_param_6, "ns2:ValidarResolucionImssResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__ValidarResolucionImssResponse(soap, &_param_6, "ns2:ValidarResolucionImssResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__MontosFechasDatamart_(struct soap *soap)
{	struct ns2__MontosFechasDatamart_ soap_tmp_ns2__MontosFechasDatamart_;
	struct ns2__MontosFechasDatamartResponse _param_7;
	soap_default_ns2__MontosFechasDatamartResponse(soap, &_param_7);
	soap_default_ns2__MontosFechasDatamart_(soap, &soap_tmp_ns2__MontosFechasDatamart_);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__MontosFechasDatamart_(soap, &soap_tmp_ns2__MontosFechasDatamart_, "ns2:MontosFechasDatamart", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__MontosFechasDatamart_(soap, soap_tmp_ns2__MontosFechasDatamart_.inParam, _param_7);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__MontosFechasDatamartResponse(soap, &_param_7);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__MontosFechasDatamartResponse(soap, &_param_7, "ns2:MontosFechasDatamartResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__MontosFechasDatamartResponse(soap, &_param_7, "ns2:MontosFechasDatamartResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__consultarResolucion(struct soap *soap)
{	struct ns2__consultarResolucion soap_tmp_ns2__consultarResolucion;
	struct ns2__consultarResolucionResponse _param_8;
	soap_default_ns2__consultarResolucionResponse(soap, &_param_8);
	soap_default_ns2__consultarResolucion(soap, &soap_tmp_ns2__consultarResolucion);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__consultarResolucion(soap, &soap_tmp_ns2__consultarResolucion, "ns2:consultarResolucion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__consultarResolucion(soap, soap_tmp_ns2__consultarResolucion.inParam, _param_8);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__consultarResolucionResponse(soap, &_param_8);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__consultarResolucionResponse(soap, &_param_8, "ns2:consultarResolucionResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__consultarResolucionResponse(soap, &_param_8, "ns2:consultarResolucionResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__ConsultarComplementoResolucion(struct soap *soap)
{	struct ns2__ConsultarComplementoResolucion soap_tmp_ns2__ConsultarComplementoResolucion;
	struct ns2__ConsultarComplementoResolucionResponse _param_9;
	soap_default_ns2__ConsultarComplementoResolucionResponse(soap, &_param_9);
	soap_default_ns2__ConsultarComplementoResolucion(soap, &soap_tmp_ns2__ConsultarComplementoResolucion);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__ConsultarComplementoResolucion(soap, &soap_tmp_ns2__ConsultarComplementoResolucion, "ns2:ConsultarComplementoResolucion", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__ConsultarComplementoResolucion(soap, soap_tmp_ns2__ConsultarComplementoResolucion.inParam, _param_9);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__ConsultarComplementoResolucionResponse(soap, &_param_9);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__ConsultarComplementoResolucionResponse(soap, &_param_9, "ns2:ConsultarComplementoResolucionResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__ConsultarComplementoResolucionResponse(soap, &_param_9, "ns2:ConsultarComplementoResolucionResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__ConsultarResolucionTotalImss(struct soap *soap)
{	struct ns2__ConsultarResolucionTotalImss soap_tmp_ns2__ConsultarResolucionTotalImss;
	struct ns2__ConsultarResolucionTotalImssResponse _param_10;
	soap_default_ns2__ConsultarResolucionTotalImssResponse(soap, &_param_10);
	soap_default_ns2__ConsultarResolucionTotalImss(soap, &soap_tmp_ns2__ConsultarResolucionTotalImss);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__ConsultarResolucionTotalImss(soap, &soap_tmp_ns2__ConsultarResolucionTotalImss, "ns2:ConsultarResolucionTotalImss", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__ConsultarResolucionTotalImss(soap, soap_tmp_ns2__ConsultarResolucionTotalImss.inParam, _param_10);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__ConsultarResolucionTotalImssResponse(soap, &_param_10);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__ConsultarResolucionTotalImssResponse(soap, &_param_10, "ns2:ConsultarResolucionTotalImssResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__ConsultarResolucionTotalImssResponse(soap, &_param_10, "ns2:ConsultarResolucionTotalImssResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__COperacionesPmg(struct soap *soap)
{	struct ns2__COperacionesPmg soap_tmp_ns2__COperacionesPmg;
	struct ns2__COperacionesPmgResponse _param_11;
	soap_default_ns2__COperacionesPmgResponse(soap, &_param_11);
	soap_default_ns2__COperacionesPmg(soap, &soap_tmp_ns2__COperacionesPmg);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__COperacionesPmg(soap, &soap_tmp_ns2__COperacionesPmg, "ns2:COperacionesPmg", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__COperacionesPmg(soap, soap_tmp_ns2__COperacionesPmg.inParam, _param_11);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__COperacionesPmgResponse(soap, &_param_11);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__COperacionesPmgResponse(soap, &_param_11, "ns2:COperacionesPmgResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__COperacionesPmgResponse(soap, &_param_11, "ns2:COperacionesPmgResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__movimientosCuentas(struct soap *soap)
{	struct ns2__movimientosCuentas soap_tmp_ns2__movimientosCuentas;
	struct ns2__movimientosCuentasResponse _param_12;
	soap_default_ns2__movimientosCuentasResponse(soap, &_param_12);
	soap_default_ns2__movimientosCuentas(soap, &soap_tmp_ns2__movimientosCuentas);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__movimientosCuentas(soap, &soap_tmp_ns2__movimientosCuentas, "ns2:movimientosCuentas", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__movimientosCuentas(soap, soap_tmp_ns2__movimientosCuentas.inParam, _param_12);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__movimientosCuentasResponse(soap, &_param_12);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__movimientosCuentasResponse(soap, &_param_12, "ns2:movimientosCuentasResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__movimientosCuentasResponse(soap, &_param_12, "ns2:movimientosCuentasResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__ConsultarResolucionTotalIssste(struct soap *soap)
{	struct ns2__ConsultarResolucionTotalIssste soap_tmp_ns2__ConsultarResolucionTotalIssste;
	struct ns2__ConsultarResolucionTotalIsssteResponse _param_13;
	soap_default_ns2__ConsultarResolucionTotalIsssteResponse(soap, &_param_13);
	soap_default_ns2__ConsultarResolucionTotalIssste(soap, &soap_tmp_ns2__ConsultarResolucionTotalIssste);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__ConsultarResolucionTotalIssste(soap, &soap_tmp_ns2__ConsultarResolucionTotalIssste, "ns2:ConsultarResolucionTotalIssste", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__ConsultarResolucionTotalIssste(soap, soap_tmp_ns2__ConsultarResolucionTotalIssste.inParam, _param_13);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__ConsultarResolucionTotalIsssteResponse(soap, &_param_13);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__ConsultarResolucionTotalIsssteResponse(soap, &_param_13, "ns2:ConsultarResolucionTotalIsssteResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__ConsultarResolucionTotalIsssteResponse(soap, &_param_13, "ns2:ConsultarResolucionTotalIsssteResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__consultarSaldosPmg(struct soap *soap)
{	struct ns2__consultarSaldosPmg soap_tmp_ns2__consultarSaldosPmg;
	struct ns2__consultarSaldosPmgResponse _param_14;
	soap_default_ns2__consultarSaldosPmgResponse(soap, &_param_14);
	soap_default_ns2__consultarSaldosPmg(soap, &soap_tmp_ns2__consultarSaldosPmg);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__consultarSaldosPmg(soap, &soap_tmp_ns2__consultarSaldosPmg, "ns2:consultarSaldosPmg", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__consultarSaldosPmg(soap, soap_tmp_ns2__consultarSaldosPmg.inParam, _param_14);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__consultarSaldosPmgResponse(soap, &_param_14);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__consultarSaldosPmgResponse(soap, &_param_14, "ns2:consultarSaldosPmgResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__consultarSaldosPmgResponse(soap, &_param_14, "ns2:consultarSaldosPmgResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__consultarAportaciones(struct soap *soap)
{	struct ns2__consultarAportaciones soap_tmp_ns2__consultarAportaciones;
	struct ns2__consultarAportacionesResponse _param_15;
	soap_default_ns2__consultarAportacionesResponse(soap, &_param_15);
	soap_default_ns2__consultarAportaciones(soap, &soap_tmp_ns2__consultarAportaciones);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__consultarAportaciones(soap, &soap_tmp_ns2__consultarAportaciones, "ns2:consultarAportaciones", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__consultarAportaciones(soap, soap_tmp_ns2__consultarAportaciones.inParam, _param_15);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__consultarAportacionesResponse(soap, &_param_15);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__consultarAportacionesResponse(soap, &_param_15, "ns2:consultarAportacionesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__consultarAportacionesResponse(soap, &_param_15, "ns2:consultarAportacionesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__ConsultarResolucionTotalImssRI(struct soap *soap)
{	struct ns2__ConsultarResolucionTotalImssRI soap_tmp_ns2__ConsultarResolucionTotalImssRI;
	struct ns2__ConsultarResolucionTotalImssRIResponse _param_16;
	soap_default_ns2__ConsultarResolucionTotalImssRIResponse(soap, &_param_16);
	soap_default_ns2__ConsultarResolucionTotalImssRI(soap, &soap_tmp_ns2__ConsultarResolucionTotalImssRI);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__ConsultarResolucionTotalImssRI(soap, &soap_tmp_ns2__ConsultarResolucionTotalImssRI, "ns2:ConsultarResolucionTotalImssRI", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__ConsultarResolucionTotalImssRI(soap, soap_tmp_ns2__ConsultarResolucionTotalImssRI.inParam, _param_16);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__ConsultarResolucionTotalImssRIResponse(soap, &_param_16);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__ConsultarResolucionTotalImssRIResponse(soap, &_param_16, "ns2:ConsultarResolucionTotalImssRIResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__ConsultarResolucionTotalImssRIResponse(soap, &_param_16, "ns2:ConsultarResolucionTotalImssRIResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__ConsultarSieforeCtaRegimen(struct soap *soap)
{	struct ns2__ConsultarSieforeCtaRegimen soap_tmp_ns2__ConsultarSieforeCtaRegimen;
	struct ns2__ConsultarSieforeCtaRegimenResponse _param_17;
	soap_default_ns2__ConsultarSieforeCtaRegimenResponse(soap, &_param_17);
	soap_default_ns2__ConsultarSieforeCtaRegimen(soap, &soap_tmp_ns2__ConsultarSieforeCtaRegimen);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__ConsultarSieforeCtaRegimen(soap, &soap_tmp_ns2__ConsultarSieforeCtaRegimen, "ns2:ConsultarSieforeCtaRegimen", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__ConsultarSieforeCtaRegimen(soap, soap_tmp_ns2__ConsultarSieforeCtaRegimen.inParam, _param_17);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__ConsultarSieforeCtaRegimenResponse(soap, &_param_17);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__ConsultarSieforeCtaRegimenResponse(soap, &_param_17, "ns2:ConsultarSieforeCtaRegimenResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__ConsultarSieforeCtaRegimenResponse(soap, &_param_17, "ns2:ConsultarSieforeCtaRegimenResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__ConsultarSaldoVol(struct soap *soap)
{	struct ns2__ConsultarSaldoVol soap_tmp_ns2__ConsultarSaldoVol;
	struct ns2__ConsultarSaldoVolResponse _param_18;
	soap_default_ns2__ConsultarSaldoVolResponse(soap, &_param_18);
	soap_default_ns2__ConsultarSaldoVol(soap, &soap_tmp_ns2__ConsultarSaldoVol);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__ConsultarSaldoVol(soap, &soap_tmp_ns2__ConsultarSaldoVol, "ns2:ConsultarSaldoVol", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__ConsultarSaldoVol(soap, soap_tmp_ns2__ConsultarSaldoVol.inParam, _param_18);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__ConsultarSaldoVolResponse(soap, &_param_18);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__ConsultarSaldoVolResponse(soap, &_param_18, "ns2:ConsultarSaldoVolResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__ConsultarSaldoVolResponse(soap, &_param_18, "ns2:ConsultarSaldoVolResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__ConsultaSaldoVivienda(struct soap *soap)
{	struct ns2__ConsultaSaldoVivienda soap_tmp_ns2__ConsultaSaldoVivienda;
	struct ns2__ConsultaSaldoViviendaResponse _param_19;
	soap_default_ns2__ConsultaSaldoViviendaResponse(soap, &_param_19);
	soap_default_ns2__ConsultaSaldoVivienda(soap, &soap_tmp_ns2__ConsultaSaldoVivienda);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__ConsultaSaldoVivienda(soap, &soap_tmp_ns2__ConsultaSaldoVivienda, "ns2:ConsultaSaldoVivienda", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__ConsultaSaldoVivienda(soap, soap_tmp_ns2__ConsultaSaldoVivienda.inParam, _param_19);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__ConsultaSaldoViviendaResponse(soap, &_param_19);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__ConsultaSaldoViviendaResponse(soap, &_param_19, "ns2:ConsultaSaldoViviendaResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__ConsultaSaldoViviendaResponse(soap, &_param_19, "ns2:ConsultaSaldoViviendaResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__ConsultaAportacionesPosteriores(struct soap *soap)
{	struct ns2__ConsultaAportacionesPosteriores soap_tmp_ns2__ConsultaAportacionesPosteriores;
	struct ns2__ConsultaAportacionesPosterioresResponse _param_20;
	soap_default_ns2__ConsultaAportacionesPosterioresResponse(soap, &_param_20);
	soap_default_ns2__ConsultaAportacionesPosteriores(soap, &soap_tmp_ns2__ConsultaAportacionesPosteriores);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__ConsultaAportacionesPosteriores(soap, &soap_tmp_ns2__ConsultaAportacionesPosteriores, "ns2:ConsultaAportacionesPosteriores", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__ConsultaAportacionesPosteriores(soap, soap_tmp_ns2__ConsultaAportacionesPosteriores.inParam, _param_20);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__ConsultaAportacionesPosterioresResponse(soap, &_param_20);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__ConsultaAportacionesPosterioresResponse(soap, &_param_20, "ns2:ConsultaAportacionesPosterioresResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__ConsultaAportacionesPosterioresResponse(soap, &_param_20, "ns2:ConsultaAportacionesPosterioresResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__CConsultarResolusionRetAportaciones(struct soap *soap)
{	struct ns2__CConsultarResolusionRetAportaciones soap_tmp_ns2__CConsultarResolusionRetAportaciones;
	struct ns2__CConsultarResolusionRetAportacionesResponse _param_21;
	soap_default_ns2__CConsultarResolusionRetAportacionesResponse(soap, &_param_21);
	soap_default_ns2__CConsultarResolusionRetAportaciones(soap, &soap_tmp_ns2__CConsultarResolusionRetAportaciones);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__CConsultarResolusionRetAportaciones(soap, &soap_tmp_ns2__CConsultarResolusionRetAportaciones, "ns2:CConsultarResolusionRetAportaciones", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__CConsultarResolusionRetAportaciones(soap, soap_tmp_ns2__CConsultarResolusionRetAportaciones.inParam, _param_21);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__CConsultarResolusionRetAportacionesResponse(soap, &_param_21);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__CConsultarResolusionRetAportacionesResponse(soap, &_param_21, "ns2:CConsultarResolusionRetAportacionesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__CConsultarResolusionRetAportacionesResponse(soap, &_param_21, "ns2:CConsultarResolusionRetAportacionesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__CConsultarSaldoRecuperar(struct soap *soap)
{	struct ns2__CConsultarSaldoRecuperar soap_tmp_ns2__CConsultarSaldoRecuperar;
	struct ns2__CConsultarSaldoRecuperarResponse _param_22;
	soap_default_ns2__CConsultarSaldoRecuperarResponse(soap, &_param_22);
	soap_default_ns2__CConsultarSaldoRecuperar(soap, &soap_tmp_ns2__CConsultarSaldoRecuperar);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__CConsultarSaldoRecuperar(soap, &soap_tmp_ns2__CConsultarSaldoRecuperar, "ns2:CConsultarSaldoRecuperar", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__CConsultarSaldoRecuperar(soap, soap_tmp_ns2__CConsultarSaldoRecuperar.inParam, _param_22);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__CConsultarSaldoRecuperarResponse(soap, &_param_22);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__CConsultarSaldoRecuperarResponse(soap, &_param_22, "ns2:CConsultarSaldoRecuperarResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__CConsultarSaldoRecuperarResponse(soap, &_param_22, "ns2:CConsultarSaldoRecuperarResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__CConsultarFechaLiquida(struct soap *soap)
{	struct ns2__CConsultarFechaLiquida soap_tmp_ns2__CConsultarFechaLiquida;
	struct ns2__CConsultarFechaLiquidaResponse _param_23;
	soap_default_ns2__CConsultarFechaLiquidaResponse(soap, &_param_23);
	soap_default_ns2__CConsultarFechaLiquida(soap, &soap_tmp_ns2__CConsultarFechaLiquida);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__CConsultarFechaLiquida(soap, &soap_tmp_ns2__CConsultarFechaLiquida, "ns2:CConsultarFechaLiquida", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__CConsultarFechaLiquida(soap, soap_tmp_ns2__CConsultarFechaLiquida.inParam, _param_23);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__CConsultarFechaLiquidaResponse(soap, &_param_23);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__CConsultarFechaLiquidaResponse(soap, &_param_23, "ns2:CConsultarFechaLiquidaResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__CConsultarFechaLiquidaResponse(soap, &_param_23, "ns2:CConsultarFechaLiquidaResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__CConsultarNumMensualidad(struct soap *soap)
{	struct ns2__CConsultarNumMensualidad soap_tmp_ns2__CConsultarNumMensualidad;
	struct ns2__CConsultarNumMensualidadResponse _param_24;
	soap_default_ns2__CConsultarNumMensualidadResponse(soap, &_param_24);
	soap_default_ns2__CConsultarNumMensualidad(soap, &soap_tmp_ns2__CConsultarNumMensualidad);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__CConsultarNumMensualidad(soap, &soap_tmp_ns2__CConsultarNumMensualidad, "ns2:CConsultarNumMensualidad", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__CConsultarNumMensualidad(soap, soap_tmp_ns2__CConsultarNumMensualidad.inParam, _param_24);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__CConsultarNumMensualidadResponse(soap, &_param_24);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__CConsultarNumMensualidadResponse(soap, &_param_24, "ns2:CConsultarNumMensualidadResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__CConsultarNumMensualidadResponse(soap, &_param_24, "ns2:CConsultarNumMensualidadResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__consultarSaldosPenMinGar(struct soap *soap)
{	struct ns2__consultarSaldosPenMinGar soap_tmp_ns2__consultarSaldosPenMinGar;
	struct ns2__consultarSaldosPenMinGarResponse _param_25;
	soap_default_ns2__consultarSaldosPenMinGarResponse(soap, &_param_25);
	soap_default_ns2__consultarSaldosPenMinGar(soap, &soap_tmp_ns2__consultarSaldosPenMinGar);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__consultarSaldosPenMinGar(soap, &soap_tmp_ns2__consultarSaldosPenMinGar, "ns2:consultarSaldosPenMinGar", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns2__consultarSaldosPenMinGar(soap, soap_tmp_ns2__consultarSaldosPenMinGar.inParam, _param_25);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__consultarSaldosPenMinGarResponse(soap, &_param_25);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__consultarSaldosPenMinGarResponse(soap, &_param_25, "ns2:consultarSaldosPenMinGarResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__consultarSaldosPenMinGarResponse(soap, &_param_25, "ns2:consultarSaldosPenMinGarResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
